#!/usr/bin/env bash
# Generates deploy/control-plane/.env with randomly generated, strong
# credentials for the control-plane compose stack (Postgres + MinIO).
#
#   deploy/control-plane/generate-env.sh
#
# Idempotent: never overwrites an existing .env. Secrets are written with
# 0600 perms. The generated .env is git-ignored and must stay on the host.
set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  echo "  .env already exists — leaving it untouched (re-run to keep secrets stable)."
  echo "  If you need fresh credentials, delete $ENV_FILE and re-run."
  exit 0
fi

rand_hex() { openssl rand -hex 16; }   # 32 hex chars (128 bits) — strong
rand_user() { openssl rand -hex 4; }   # 8 hex chars — random but readable

PG_USER="herdr_$(rand_user)"
PG_PASS="$(rand_hex)"
MINIO_USER="herdr_$(rand_user)"
MINIO_PASS="$(rand_hex)"

# HERDR_CP_WEB_BIND controls which host interface the control-plane web UI is
# published on. Leave at 127.0.0.1 for loopback-only, or set it to this
# machine's Tailscale IP (e.g. `tailscale ip -4`) to expose on dev.lan.
WEB_BIND="${HERDR_CP_WEB_BIND:-127.0.0.1}"

cat > "$ENV_FILE" <<EOF
# Auto-generated by generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Do not commit. Keep this file on the host only (0600).

# Postgres
HERDR_CP_PG_USER=$PG_USER
HERDR_CP_PG_PASSWORD=$PG_PASS

# MinIO (S3 drop-in for RustFS)
HERDR_CP_MINIO_USER=$MINIO_USER
HERDR_CP_MINIO_PASSWORD=$MINIO_PASS

# Which host interface the control-plane web UI is published on.
#  127.0.0.1        = loopback only (default, safe)
#  <tailnet-ip>     = reachable on dev.lan (Tailnet is the trust boundary)
HERDR_CP_WEB_BIND=$WEB_BIND
EOF

chmod 600 "$ENV_FILE"
echo "  Wrote $ENV_FILE (0600)."
echo "  Postgres user:  $PG_USER"
echo "  MinIO user:     $MINIO_USER"
echo "  Web bind:       $WEB_BIND"
echo
echo "  Next: docker compose up -d --build"
echo "  To expose on dev.lan, set HERDR_CP_WEB_BIND to \$(tailscale ip -4) first,"
echo "  or edit $ENV_FILE and restart the web service."
